### ISSUE TITLE
The docs could use more consistent vocabulary

### ISSUE THREAD

**Issue by alecrem** [polyblocksapp/docs#2]
### What I found

A number of words are used interchangeably:

1. Editions, tokens or NFTs
1. Minting or generating, 

Also, minting is rightfully used for both the artwork and each subsequent NFT (edition), but different wording might be more helpful.

#### 1. Editions, tokens or NFTs

- Consolidate to: tokens
- When explained: tokens (NFTs, also called "editions" on other platforms)

#### 2. Minting or generating, 

- Consolidate to: minting
- When explained: minting (a process comprising generating a unique piece and minting a token with it)

#### Minting an artwork vs. minting a token

- Minting an artwork → minting an artwork
- Minting a token → minting

### What to go from here

I would be happy to open a PR with the needed changes if you decide on a way to consolidate the vocabulary.

**Comment by polyblocksio** [comment]
@alecrem Good suggestions and totally agree with the proposal. I really like the explanations to describe the two technical words in a plain way :)

Also it should be much nicer if we mention that we have two different "minting" to avoid possible misunderstandings for the beginners. (I personally didn't get the concept of minting when I first joined hic et nunc, haha)

What do you think?

**Comment by alecrem** [comment]
Happy that we are on the same page about the sets of words with the same meaning.

About the two meanings of "minting", I suggest using "minting" when it's a token because it's the more common meaning of the word -- the only one most users will ever experience. Conversely, minting a new artwork should never be referred as just "minting" to avoid confusion with the other meaning.

I thought for a bit but could not think about a better word for "minting (an artwork that will generate a number of subsequently minted tokens)". Do you know if any of PB's competitors use any specific vocabulary for this?

**Comment by polyblocksio** [comment]
@alecrem The competitors are using "mint", "publish", "create" or "upload". 
Many artists so far come from fxhash, so it should be better to follow their vocabulary here, so "mint" it the best now?
