### ISSUE TITLE
Costs on the about page could be explained in more detail

### ISSUE THREAD

**Issue by alecrem** [polyblocksapp/docs#3]
I think it could be more specific. Reading the costs section left me with these questions. The replies or explanations for some of these might be good additions to the `about` page.

> Polyblocks charges 3% of platform fees

- 3% of what amount?
- In what kind of transaction? When a user mints a token from an artwork?

> and so for the whole duration of the beta.

- Does this mean that the pricing will not change until PB is out of beta?
- Does it mean that you expect it to change when you go out of beta?

> You do not have to pay any extra charge for us.

- Do artists have to pay to mint an artwork?
- Just the gas for a single transaction?

**Comment by polyblocksio** [comment]
Yes, it should be described in detail.

> 3% of what amount?

3% of sales upon each transaction :)

> In what kind of transaction? When a user mints a token from an artwork?

- minting a token (Charge 0.3 MATIC for every 10 MATIC transaction.)
- trading a token in the secondary market (same as above)

> Does this mean that the pricing will not change until PB is out of beta?

Will not change during beta, but might be changed if the running costs significantly exceed the revenue.. (but I don't think it's gonna happen so far)

> Does it mean that you expect it to change when you go out of beta?

No plans yet. Need more transactions to estimate the running costs, but it shouldn't be drastic even if it's changed. (maybe between 3 - 5% of sales)

> Do artists have to pay to mint an artwork?

the gas only.

> Just the gas for a single transaction?

Exactly!

**Comment by alecrem** [comment]
Thank you! I'll draft some changes to include more of this information on the page, if you don't mind.

Please keep the issue open if you are okay with a pr with such changes.

**Comment by polyblocksio** [comment]
@alecrem Of course, it's very very welcome 💯 I'll keep this open :)
